### ISSUE TITLE
Not index my flipnote

### ISSUE THREAD

**Issue by GK-Gaming** [NotImplementedLife/FSPDS#13]
This is wrong, my fipnotes is correct looks this:
![grafik](https://github.com/NotImplementedLife/FSPDS/assets/153021118/7db770dd-279e-4c2e-9c6e-25bb583a82c6)

But is say on DS 0 flipnotes in folder... why?

**Comment by NotImplementedLife** [comment]
Most likely it has to do with the fact that the file names are not in the original format (e.g. G35B20_0909841CDBEB1_002.ppm). The app assumes flipnote files are named this way and ignores everything else on the filesystem. Either way that 5.1MiB flipnote wouldn't be displayable/playable with FSPDS.

**Comment by GK-Gaming** [comment]
i find out the name is the 28 long or not show, all flipnote here were corrupt and I could that recover, so one is 5.1MB (not really) but they work

**Comment by NotImplementedLife** [comment]
Here is a small fix that should work in your case for now: 

https://github.com/NotImplementedLife/FSPDS/releases/tag/V1.0.90343508R. 

FPSDS should be able to detect your files while indexing folder. 

![image](https://github.com/NotImplementedLife/FSPDS/assets/70803115/60fc972e-3afd-4a2a-ad95-91c49267a11b)

**Comment by GK-Gaming** [comment]
thanks!

**Comment by NotImplementedLife** [comment]
You're welcome! I'll close this issue for now. But the changes will be refined and included in the next major release. Thank you for using FSPDS!
