### ISSUE TITLE
Alternate flipnote browse locations

### ISSUE THREAD

**Issue by tomrow** [NotImplementedLife/FSPDS#2]
This app looks for movies in the "/flipnotes" folder, but it would also be nice to have the option to search the "/private/ds/app/4b475556" folder, the path on DSi SD cards where the official Flipnote app stored saved flipnotes. It would save a lot of time relocating flipnotes after copying them to other systems.

**Comment by NotImplementedLife** [comment]
Hi, tomrow! Thanks for your great suggestion! Now the flipnotes can be loaded from "/flipnotes", as well as from "/private/ds/app/4b4755XX" paths, where XX is the DSi region-specific code. 
This is a temporary test ROM:
https://github.com/NotImplementedLife/FSPDS/releases/tag/V0.3.41164628D
Expect a full release as soon as I assure the code is dealing with all the corner test cases (e.g. empty directories, missing paths etc)
